namespace TravelPal.Enums
{
    public enum EuropeanCountries
    {
        Austria,
        Belgium,
        Bulgaria,
        Croatia,
        Republic_of_Cyprus,
        Czech_Republic,
        Denmark,
        Estonia,
        Finland,
        France,
        Germany,
        Greece,
        Hungary,
        Ireland,
        Italy,
        Latvia,
        Lithuania,
        Luxembourg,
        Malta,
        Netherlands,
        Poland,
        Portugal,
        Romania,
        Slovakia,
        Slovenia,
        Spain,
        Sweden
    }
}
